### PR TITLE
Enable highlighting for const, let and other storage types (in JS & TS)

### PR DESCRIPTION
**Pull request by Soupertonic**
This theme is really nice and I noticed that `const`, `let` and other storage types are not highlighted. I added the appropriate textmate scope so that it highlights the mentioned storage types / keywords.

That's how it highlights right now:
image

Cheers.

### CODE REVIEW

**Comment by lunacookies** [comment]
Aren’t `let` and `const` keywords, not types?

**Comment by Soupertonic** [comment]
Apparently and according to VS Code, no. 
image

**Comment by lunacookies** [comment]
###### Keywords vs types

On [this list of JS keywords](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#keywords) you can see that `const` and `var` are included, while [this list of JS types](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#primitive_values) doesn’t include `const` or `var`.

###### Why does VS Code show that `const` and `var` are types, then?

Honestly, I have no idea. That TextMate scope from before,  `storage.type`, is also present across the original TextMate itself, as well as Sublime Text (which, like VS Code, inherited TextMate’s syntax highlighting and theming system). In my experience TextMate grammars are typically full of these weird inconsistencies and nonsensical scope names.

As a counterpoint, every single semantic highlighting implementation I’ve come across handles this correctly. Semantic highlighting is implemented by language servers, which in turn are often implemented by the same team which develops the language itself. I’d say code highlighting based on the work of compiler engineers instead of the inherited highlighting of an editor [which peaked in 2007](https://trends.google.com/trends/explore?date=all&q=textmate) is more likely to be accurate.

The default VS Code theme chooses to ignore the idiosyncrasies of TextMate highlighting and highlights `const`, `var`, `let` and `struct` as keywords (dark blue), while highlighting `number` and `Bar` as types (green):

Screenshot 2022-11-13 at 12 38 45 pm

Screenshot 2022-11-13 at 12 42 09 pm

Screenshot 2022-11-13 at 12 39 54 pm

Far too many other themes don’t recognize these factors and just go along with the literal TextMate scope names, perhaps most famously Monokai in Sublime Text:

Screenshot 2022-11-13 at 12 53 28 pm

Ignoring how it highlights class definitions in green, Monokai goes along with TextMate and highlights `class` (a keyword) the same as `Bar` (a class).

In Noel/Yuru I sidestep TextMate highlighting’s antics and try to match the semantics of the language as closely as possible.

###### Manual editing

By the way, if it’s not too much effort would you mind editing the generator in `src/main.rs` instead of editing the JSON output directly? That way changes get applied to both themes automatically. Thanks :)

**Comment by Soupertonic** [comment]
<details>
  <summary><b>Added scopes</b></summary>

  ###### Secondary Accent 2
  - `storage.type` for `const`, `let` and `var` in JS/TS
  - `support.type.primitive` for `string`, `number` and other primitives in JS/TS
  - `entity.name.tag.html` for any tag in HTML

  ###### Primary Accent
  - `meta.property-value.css` for any constant values (`none`, `unset`, `initial` and more) in CSS/SASS/SCSS etc.
</details>

<details>
  <summary><b>Before</b></summary>

before2
before3
before4
before1
</details>

<details>
  <summary><b>After</b></summary>

after4
after3
after2
after1
</details>

**Comment by lunacookies** [comment]
Awesome, thanks so much!

**Comment by lunacookies** [comment]
Published in v2.1.0.

**Pull request merged**
